"""
Watchlist & Scanner Operations Router.
Handles: watchlist CRUD, ticker search, live watchlist data, historical candles.
"""

import os
import json
from datetime import datetime, timedelta
from fastapi import APIRouter, Request
from fastapi.responses import JSONResponse

import config
from routers.shared import load_watchlist, load_symbol_to_token

router = APIRouter()


@router.get("/api/watchlist")
def get_watchlist():
    """
    Returns the parsed watchlist.
    """
    return JSONResponse(load_watchlist())


@router.get("/api/search")
def search_tickers(q: str = ""):
    """
    Filters the whitelisted Nifty 50 tickers based on the search query.
    """
    query = q.strip().upper()
    if not query:
        return JSONResponse([])
        
    results = []
    for ticker in config.NIFTY_50_TICKERS:
        if query in ticker:
            results.append({"ticker": ticker, "name": f"{ticker} (NSE Equity)"})
            
    return JSONResponse(results[:10])


@router.post("/api/watchlist/add")
async def add_to_watchlist(request: Request):
    """
    Adds a symbol to the Buy or Sell watchlist columns.
    Ensures a symbol only exists in one column at a time.
    """
    try:
        data = await request.json()
        symbol = data.get("symbol", "").upper()
        direction = data.get("direction", "buy").lower()
    except Exception:
        return JSONResponse({"status": "error", "message": "Invalid request payload"}, status_code=400)
        
    if not symbol or symbol not in config.NIFTY_50_TICKERS:
        return JSONResponse({"status": "error", "message": "Invalid or non-whitelisted symbol"}, status_code=400)
        
    if direction not in ["buy", "sell"]:
        direction = "buy"
        
    watchlist = load_watchlist()
    
    # Remove from other column if present to prevent duplicates
    other_dir = "sell" if direction == "buy" else "buy"
    if symbol in watchlist.get(other_dir, []):
        watchlist[other_dir].remove(symbol)
        
    if symbol not in watchlist.get(direction, []):
        watchlist[direction].append(symbol)
        
    with open(config.WATCHLIST_FILE, "w") as f:
        json.dump(watchlist, f, indent=4)
        
    return JSONResponse({"status": "success", "message": f"Added {symbol} to {direction} watchlist."})


@router.post("/api/watchlist/remove")
async def remove_from_watchlist(request: Request):
    """
    Removes a symbol from all watchlist columns.
    """
    try:
        data = await request.json()
        symbol = data.get("symbol", "").upper()
    except Exception:
        return JSONResponse({"status": "error", "message": "Invalid request payload"}, status_code=400)
        
    watchlist = load_watchlist()
    removed = False
    
    for direction in ["buy", "sell"]:
        if symbol in watchlist.get(direction, []):
            watchlist[direction].remove(symbol)
            removed = True
            
    if removed:
        with open(config.WATCHLIST_FILE, "w") as f:
            json.dump(watchlist, f, indent=4)
        return JSONResponse({"status": "success", "message": f"Removed {symbol} from watchlist."})
        
    return JSONResponse({"status": "error", "message": f"Symbol {symbol} not found in watchlist."}, status_code=404)


@router.get("/api/watchlist/data")
def get_watchlist_data():
    """
    Returns live prices and pre-calculated technical indicators for watchlisted tickers.
    Reads metrics directly from the shared memory file generated by KiteDataLogger.
    """
    watchlist = load_watchlist()
    buy_symbols = watchlist.get("buy", [])
    sell_symbols = watchlist.get("sell", [])
    all_symbols = list(set(buy_symbols + sell_symbols))
    
    market_snapshot = {}
    if os.path.exists(config.LIVE_MARKET_DATA_FILE):
        try:
            with open(config.LIVE_MARKET_DATA_FILE, "r") as f:
                market_snapshot = json.load(f)
        except Exception:
            pass
            
    results = []
    for symbol in all_symbols:
        direction = "BUY" if symbol in buy_symbols else "SELL"
        symbol_data = market_snapshot.get(symbol, {})
        
        # Merge technical data if available, otherwise return empty placeholders
        ticker_metrics = {
            "symbol": symbol,
            "direction": direction,
            "ltp": symbol_data.get("ltp", None),
            "change": symbol_data.get("change", 0.0),
            "volume": symbol_data.get("volume", 0),
            "adr_percentage": symbol_data.get("adr_percentage", 0.0),
            "adr_absolute": symbol_data.get("adr_absolute", 0.0),
            
            # Timeframe: 5-minute indicators
            "m5_vwap": symbol_data.get("vwap_5m", None),
            "m5_ema20": symbol_data.get("ema20_5m", None),
            "m5_ema50": symbol_data.get("ema50_5m", None),
            "m5_ema200": symbol_data.get("ema200_5m", None),
            "m5_rsi": symbol_data.get("rsi_5m", None),
            
            # Timeframe: 15-minute indicators
            "m15_vwap": symbol_data.get("vwap_15m", None),
            "m15_ema20": symbol_data.get("ema20_15m", None),
            "m15_ema50": symbol_data.get("ema50_15m", None),
            "m15_ema200": symbol_data.get("ema200_15m", None),
            "m15_rsi": symbol_data.get("rsi_15m", None),
            
            "last_update": symbol_data.get("last_update", None)
        }
        results.append(ticker_metrics)
        
    return JSONResponse({"watchlist_data": results})


@router.get("/api/history/{symbol}")
def get_history(symbol: str, interval: str = "5minute", days: int = 5):
    """
    Returns historical candle data from Zerodha for the specified symbol and interval.
    Format is formatted specifically for TradingView Lightweight Charts.
    """
    symbol = symbol.upper()
    sym_to_tok = load_symbol_to_token()
    token = sym_to_tok.get(symbol)
    if not token:
        return JSONResponse({"status": "error", "message": f"Symbol {symbol} token mapping not found."}, status_code=400)
        
    try:
        from kite_auth_manager import get_kite_client
        kite = get_kite_client()
        to_date = datetime.now()
        from_date = to_date - timedelta(days=days)
        
        # Verify call parameters against local connect.py reference
        # historical_data(self, instrument_token, from_date, to_date, interval, continuous=False, oi=False)
        data = kite.historical_data(
            instrument_token=token,
            from_date=from_date,
            to_date=to_date,
            interval=interval
        )
        
        formatted_data = []
        for d in data:
            dt = d["date"]
            timestamp = int(dt.timestamp())
            formatted_data.append({
                "time": timestamp,
                "open": d["open"],
                "high": d["high"],
                "low": d["low"],
                "close": d["close"],
                "volume": d["volume"]
            })
            
        return JSONResponse({"status": "success", "data": formatted_data})
    except Exception as e:
        return JSONResponse({"status": "error", "message": str(e)}, status_code=500)


@router.get("/api/radar/candidates")
def get_radar_candidates():
    """
    Returns persistent active radar candidates enriched with live indicators and ORB ranges.
    """
    import os
    import json
    import config

    candidates = {}
    if os.path.exists(config.RADAR_CANDIDATES_FILE):
        try:
            with open(config.RADAR_CANDIDATES_FILE, "r") as f:
                candidates = json.load(f)
        except Exception:
            pass

    # Load live telemetry snapshot
    market_snapshot = {}
    if os.path.exists(config.LIVE_MARKET_DATA_FILE):
        try:
            with open(config.LIVE_MARKET_DATA_FILE, "r") as f:
                market_snapshot = json.load(f)
        except Exception:
            pass

    from orb_manager import ORBManagerMixin
    class QuickORB(ORBManagerMixin):
        def __init__(self):
            self.orb_ranges = {}
            self.symbol_to_token = {}
            if os.path.exists(config.INSTRUMENT_MAPPING_FILE):
                try:
                    with open(config.INSTRUMENT_MAPPING_FILE, "r") as f:
                        mapping = json.load(f)
                        self.symbol_to_token = {k: int(v) for k, v in mapping.get("symbol_to_token", {}).items()}
                except Exception:
                    pass
        def log_message(self, msg, is_error=False):
            pass
    
    orb_loader = QuickORB()

    enriched_candidates = []
    for symbol, cand in candidates.items():
        ticker_data = market_snapshot.get(symbol, {})
        
        orb_high = None
        orb_low = None
        try:
            orb = orb_loader.establish_single_orb_range(symbol)
            if orb:
                orb_high = orb["high"]
                orb_low = orb["low"]
        except Exception:
            pass

        enriched_candidates.append({
            "symbol": symbol,
            "state": cand.get("state"),
            "direction": cand.get("direction"),
            "spike_price": cand.get("spike_price"),
            "spike_open": cand.get("spike_open"),
            "spike_time": cand.get("spike_time"),
            "lowest_pullback_low": cand.get("lowest_pullback_low"),
            "highest_pullback_high": cand.get("highest_pullback_high"),
            
            # Telemetry
            "ltp": ticker_data.get("ltp"),
            "ema20_5m": ticker_data.get("ema20_5m"),
            "prev_high_5m": ticker_data.get("prev_high_5m"),
            "prev_low_5m": ticker_data.get("prev_low_5m"),
            "vwap_5m": ticker_data.get("vwap_5m"),
            "orb_high": orb_high,
            "orb_low": orb_low
        })

    return JSONResponse({"status": "success", "candidates": enriched_candidates})

